import { NextPage, Metadata } from "next";

import SwiperCarousel from "@/components/modules/home/Swiper";

export const metadata: Metadata = {
    title: 'TeknoInsight - Home',
    description: 'Generated by create next app',
  };


const Home: NextPage = () => {
    return(
        <>
            <SwiperCarousel />
        </>
    )
}

export default Home;