import { NextPage, Metadata } from "next";

import SwiperCarousel from "@/components/modules/Swiper";
import Content from "@/components/modules/Content";

//dummy
import { posts, sidebarData } from "@/utils/dummy/Data";

export const metadata: Metadata = {
    title: 'TeknoInsight - Home',
    description: 'Generated by create next app',
  };


const Page: NextPage = () => {
    return(
        <>
            <SwiperCarousel />
            <Content contentData={posts} sidebarData={sidebarData} />
        </>
    )
}

export default Page;