import { NextPage, Metadata } from "next";

export const metadata: Metadata = {
    title: 'TeknoInsight - Home',
    description: 'Generated by create next app',
  };


const Home: NextPage = () => {
    return(
        <>
        </>
    )
}

export default Home;