import type { Metadata } from 'next'
import Provider from '@/lib/Provider'

import "../assets/css/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: 'Hardware Haven | Your reliable digital solution',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      <body>
        <Provider>
          <main>
            {children}
          </main>
          </Provider>
      </body>
    </html>
  );
}