import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'TeknoInsight - Not Found',
    description: 'Generated by create next app',
  };

export default function NotFound() {
    return <h1>Not Found</h1>
}