import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/ui/header/Header";
import { HeaderProvider } from "@/lib/context/HeaderContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TeknoInsight - Your Most Reliable Tech Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary`}>
        <HeaderProvider>
          <Header />
        </HeaderProvider>
        {children}
      </body>
    </html>
  );
}
