import { NextPage, Metadata } from "next";

import SwiperCarousel from "@/components/modules/Swiper";
import HomeContent from "@/components/modules/Content";

//dummy
import { posts, categories, sidebarData } from "@/utils/dummy/Data";

export const metadata: Metadata = {
    title: 'TeknoInsight - Tutorials',
    description: 'Generated by create next app',
  };


const Page: NextPage = () => {
    return(
        <>
            <SwiperCarousel />
            <HomeContent contentData={posts} categoryData={categories} sidebarData={sidebarData} />
        </>
    )
}

export default Page;